import React from 'react'
import Head from "next/head";
import Menu from './Menu';
import Footer from './Footer';




export default function Layout({children,title }) {
  return (
    <div>
    
      <Head>
        <title>Page next js</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        
      </Head>

      <Menu />

      <div>{children}</div>
     
   <Footer></Footer>
    </div>
  
  )
}
